### ISSUE TITLE
WebUI Error after Trigger Creation

### ISSUE THREAD

**Issue by joeltraber** [openshift/pipelines-tutorial#128]
OCP Version: 4.6.12
Openshift Pipelines Version: 1.2.3
Tekton Pipelines: v0.16.3
Tekton Triggers: v0.8.1
ClusterTasks based on Tekton Catalog 0.16

I followed the tutorial step by step. After creation of the "Event Listener" an Error on the WebUI occoured.
Clicking on the menu "Pipelines" as well as the menu "Triggers" raise the problem repeatably. The WebUI completely blanks when using the mentioned menus.

Error in developer console:
vendors~main-chunk-097f186a6bd6062a5833.min.js:159202 TypeError: Cannot read property 'name' of undefined
    at admin-pipeline~admin-tasks`~pipeline-builder-edit-page~pipeline-builder-page~pipeline-details~pipeli~8d3f0553-chunk-108e39123867785f9969.min.js:1
    at Array.map (<anonymous>)
    at b (admin-pipeline~admin-tasks`~pipeline-builder-edit-page~pipeline-builder-page~pipeline-details~pipeli~8d3f0553-chunk-108e39123867785f9969.min.js:1)
    at Array.map (<anonymous>)
    at admin-pipeline~admin-tasks`~pipeline-builder-edit-page~pipeline-builder-page~pipeline-details~pipeli~8d3f0553-chunk-108e39123867785f9969.min.js:1
    at Object.useMemo (vendors~main-chunk-097f186a6bd6062a5833.min.js:159202)
    at Object.useMemo (vendors~main-chunk-097f186a6bd6062a5833.min.js:159167)
    at v (admin-pipeline~admin-tasks`~pipeline-builder-edit-page~pipeline-builder-page~pipeline-details~pipeli~8d3f0553-chunk-108e39123867785f9969.min.js:1)
    at a.a (admin-pipeline-chunk-ba2b32ed7673e4d4b4f6.min.js:1)
    at No (vendors~main-chunk-097f186a6bd6062a5833.min.js:159202)

![webui_error](https://user-images.githubusercontent.com/5963149/106826940-31adef00-6688-11eb-8d71-6215b5c5427f.png)

**Comment by meanderix** [comment]
I'm seeing exactly the same error. After installing the tutorial I get a WSOD in the WebUI when clicking "pipelines". I'm still able to access `/triggers` and `/tasks` and it looks like the pipelinerun executes correctly (a functional instance of `vote-ui` is deployed).

**Comment by meanderix** [comment]
I managed to get a more detailed traces from `/k8s/ns/pipelines-tutorial/triggers.tekton.dev~v1alpha1~EventListener/vote-app`:

Component trace:
```
in Unknown
    in div
    in div
    in div
    in Unknown
    in t
    in t
    in div
    in Data
    in StatusBox
    in div
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in O
    in Unknown
    in O
    in Unknown
    in o
    in DetailsPage
    in Unknown
    in l
    in Unknown
    in O
    in t
    in t
    in div
    in div
    in section
    in PageSection
    in Unknown
    in O
    in div
    in div
    in DrawerMain
    in DrawerContent
    in div
    in Drawer
    in NotificationDrawer
    in Unknown
    in O
    in main
    in div
    in Page
    in div
    in DrawerContentBody
    in div
    in div
    in DrawerMain
    in DrawerContent
    in div
    in Drawer
    in Unknown
    in O
    in I
    in l
    in O
    in Unknown
    in O
    in t
    in t
    in t
    in t
```
Stack trace:
```
TypeError: Cannot read property 'name' of undefined
    at https://console-openshift-console.apps.k8s.gu.se/static/eventlistener-details-chunk-519f3e48aba2047fadf7.min.js:1:17442
    at Array.map (<anonymous>)
    at t.a (https://console-openshift-console.apps.k8s.gu.se/static/eventlistener-details-chunk-519f3e48aba2047fadf7.min.js:1:17361)
    at No (https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:160:55337)
    at Ks (https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:160:98261)
    at Bs (https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:160:84008)
    at Fs (https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:160:81035)
    at Ms (https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:160:79608)
    at https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:160:41759
    at t.unstable_runWithPriority (https://console-openshift-console.apps.k8s.gu.se/static/vendors~main-chunk-3c658109a04f0e334208.min.js:168:3878)
```

**Comment by meanderix** [comment]
Problem seem to be resolved by reverting the event listener from "tech preview 3" to "tech preview 2":
https://github.com/openshift/pipelines-tutorial/blob/release-tech-preview-3/03_triggers/04_event_listener.yaml
https://github.com/openshift/pipelines-tutorial/blob/release-tech-preview-2/03_triggers/03_event_listener.yaml

I had some other issues when deploying the event listener from "tech preview 2" (which is why i tried to update to the latest one):
```Error: admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: expected exactly one, got neither: spec.triggers[0].bindings[0].Ref, spec.triggers[0].bindings[0].Spec```
and
```Error: failed to create resource: admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "ref"```
I don't see these errors when manually editing the yaml in the WebUI.
